In [1]:
#Here each molecule is considered as a node. So here there is only one graph.

In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import AllChem
from rdkit import DataStructs
from rdkit.Chem import Descriptors
from rdkit.Chem import rdMolDescriptors
import networkx as nx

In [2]:
import matplotlib.pyplot as plt

In [3]:
df1 = pd.read_csv('./cox1_cox2_common_20260312.csv', na_values=['na'])
df1 = df1.dropna(ignore_index=True)
df1

,molecule_chembl_id,smiles,cox1_ic50,cox2_ic50
0,CHEMBL6,COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c1ccc(Cl)cc1,190.0,900.0
1,CHEMBL599,Cc1cnc(NC(=O)C2=C(O)c3ccccc3S(=O)(=O)N2C)s1,2200.0,160.0
2,CHEMBL276052,O=c1c2ccccc2c(S(=O)(=O)c2ccccc2)c(O)n1Cc1ccccc1,730.0,140.0
3,CHEMBL144819,CS(=O)(=O)Nc1cc2c(cc1Sc1ccccc1F)C(=O)CC2,50000.0,100.0
4,CHEMBL298762,CS(=O)(=O)c1ccc(C2=C(c3ccccc3)C(=O)N(c3ccccc3F...,10800.0,900.0
...,...,...,...,...
2607,CHEMBL4080317,O=CC1=Cc2cc(S(F)(F)(F)(F)F)ccc2OC1C(F)(F)F,10000.0,10000.0
2608,CHEMBL4069891,NS(=O)(=O)c1ccc(-n2nc(C(=O)OCCOc3ccc4ccc(=O)oc...,56520.0,490.0
2609,CHEMBL4076002,NS(=O)(=O)c1ccc(-n2nc(C(=O)OCCOc3ccc4ccc(=O)oc...,45350.0,770.0
2610,CHEMBL4528233,CCC1SCC(=O)N1c1c(C#N)c2n(c1C(=O)Nc1ccc(Cl)cc1)...,100000.0,1150.0
2611,CHEMBL4448607,CC(=O)n1nc(-c2ccc(Cl)cc2)cc1-c1cn(-c2ccccc2)nc...,2720.0,2790.0

In [4]:
df2 = df1.loc[:, ['cox1_ic50', 'cox2_ic50']]
df2

      cox1_ic50  cox2_ic50
0         190.0      900.0
1        2200.0      160.0
2         730.0      140.0
3       50000.0      100.0
4       10800.0      900.0
...         ...        ...
2607    10000.0    10000.0
2608    56520.0      490.0
2609    45350.0      770.0
2610   100000.0     1150.0
2611     2720.0     2790.0

[2612 rows x 2 columns]

In [5]:
for i in range(len(df2)):
    if df2['cox1_ic50'].values[i] <= 1000:
        df2.loc[i, ['cox1_ic50']] = 1
    else: 
        df2.loc[i, ['cox1_ic50']] = 0

In [6]:
for i in range(len(df2)):
    if df2['cox2_ic50'].values[i] <= 1000:
        df2.loc[i, ['cox2_ic50']] = 1
    else: 
        df2.loc[i, ['cox2_ic50']] = 0

In [7]:
newcol = []
for i in range(len(df2)):
    if df2['cox1_ic50'].values[i] == 1.0 and df2['cox2_ic50'].values[i] == 1.0:
        newcol.append('AA')
    elif df2['cox1_ic50'].values[i] == 0.0 and df2['cox2_ic50'].values[i] == 0.0:
        newcol.append('II')
    elif df2['cox1_ic50'].values[i] == 0.0 and df2['cox2_ic50'].values[i] == 1.0:
        newcol.append('IA')
    else:
        newcol.append('AI')

In [8]:
target = pd.DataFrame(data=newcol, columns=['cox1_cox2'])
target

     cox1_cox2
0           AA
1           IA
2           AA
3           IA
4           IA
...        ...
2607        II
2608        IA
2609        IA
2610        II
2611        II

[2612 rows x 1 columns]

In [9]:
y = target.values.reshape(len(df2),)
y.shape

(2612,)

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [11]:
y_label = encoder.fit_transform(y)

In [12]:
y_label

array([0, 2, 0, ..., 2, 3, 3])

In [13]:
from rdkit.Chem import SaltRemover as sr
remover = sr.SaltRemover()

In [14]:
mols = []
for i in range(len(df1)):
    try:
        mol_i = Chem.MolFromSmiles(df1['smiles'][i])
        if mol_i is None:
            print(f"[WARNING] Invalid SMILES at index {i}, skipping.")
            mols.append(None)  # Maintain indexing for multiprocessing
            continue
        mol_i = remover.StripMol(mol_i, dontRemoveEverything=True)
        mols.append(mol_i)
    except Exception as e:
        print(e)
len(mols)

2612

In [15]:
smiles_list = [df1['smiles'][i] for i in range(len(df1['smiles']))]

In [16]:
names_list = [df1['molecule_chembl_id'][i] for i in range(len(df1['molecule_chembl_id']))]

In [17]:
#Deprecated method!
FPs = [AllChem.GetMorganFingerprintAsBitVect(mols[i], radius=3, nBits=1024) for i in range(len(mols))]

[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator
[10:14:01] DEPRECATION WARNING: please use MorganGenerator

In [18]:
similarity_matrix = np.zeros((len(FPs), len(FPs)))

In [19]:
similarity_matrix.shape

(2612, 2612)

In [20]:
#only works for bit vectors or sparse count vectors, not arbitrary numerical vectors.
DataStructs.TanimotoSimilarity(FPs[10], FPs[10])

1.0

In [21]:
#Calculate the diagonal elements
for i in range(len(FPs)):
    for j in range(i, len(FPs)):  # Avoid duplicate calculations
        similarity = DataStructs.TanimotoSimilarity(FPs[i], FPs[j])
        similarity_matrix[i, j] = similarity
        similarity_matrix[j, i] = similarity

In [22]:
similarity_matrix.shape

(2612, 2612)

In [23]:
import seaborn as sns

In [24]:
similarity_matrix.min(), similarity_matrix.max(), similarity_matrix.mean()

(0.0, 1.0, 0.12891425234784723)

In [25]:
#Step 1: Compute Morgan fingerprints

In [26]:
# Suppose you have a list of SMILES strings for your molecules
def morgan_fp(smiles, radius=2, nBits=1024):
    mol = Chem.MolFromSmiles(smiles)
    fpgen = AllChem.GetMorganGenerator(fpSize=1024)
    arr_fp = fpgen.GetFingerprintAsNumPy(mol)
    return arr_fp

node_features = np.array([morgan_fp(s) for s in smiles_list])  # shape (1126, 1024)
y_label = np.array(y_label)
num_nodes = node_features.shape[0]

In [27]:
node_features.shape

(2612, 1024)

In [28]:
import numpy as np
import torch
import networkx as nx
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from torch_geometric.data import Data
from torch_geometric.utils import subgraph

In [29]:
import random
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

In [30]:
y_label

array([0, 2, 0, ..., 2, 3, 3])

In [31]:
y

array(['AA', 'IA', 'AA', ..., 'IA', 'II', 'II'], dtype=object)

In [32]:
df1.index.to_numpy()

array([   0,    1,    2, ..., 2609, 2610, 2611])

In [33]:
# Scaffold split (Bemis-Murcko), replacing random/stratified split to prevent
# structural leakage between train/val/test.
#
# Method: molecules are grouped by their Bemis-Murcko scaffold (Bemis & Murcko,
# J. Med. Chem. 1996); each scaffold group is then assigned WHOLE to a single
# split, so no two structurally near-identical molecules (sharing a scaffold)
# can appear on both sides of a train/test boundary. Scaffold groups are sorted
# largest-first and greedily filled into train, then val, then test until each
# target size is reached -- the standard convention used by MoleculeNet/DeepChem's
# ScaffoldSplitter.
#
# NOTE: unlike stratified random splitting, this does NOT guarantee proportional
# class representation in each split -- an entire rare class's molecules can
# share one scaffold and be assigned together to a single split. Given the small
# size of class IA (n=10) in this dataset, the diagnostics below explicitly check
# for this and must be reviewed before proceeding.

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from collections import defaultdict


def generate_scaffold(smiles, include_chirality=False):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return MurckoScaffold.MurckoScaffoldSmiles(mol=mol, includeChirality=include_chirality)


def scaffold_split_indices(indices, smiles_list, y_label, train_ratio=0.6, val_ratio=0.2, seed=42):
    """
    Bemis-Murcko scaffold split. indices, smiles_list, and y_label must be
    positionally aligned (same order), matching the convention of the original
    stratified_split_indices function.

    Returns train_idx, val_idx, test_idx as arrays of the original index values.
    """
    indices = np.asarray(indices)
    smiles_arr = np.asarray(smiles_list)
    y_arr = np.asarray(y_label)
    assert len(indices) == len(smiles_arr) == len(y_arr), "indices, smiles_list, y_label must be the same length and aligned"

    scaffold_to_indices = defaultdict(list)
    n_invalid = 0
    for idx, smi in zip(indices, smiles_arr):
        scaffold = generate_scaffold(smi)
        if scaffold is None:
            n_invalid += 1
            scaffold = f"__invalid_{idx}__"   # unparseable SMILES: isolate as its own group
        elif scaffold == "":
            scaffold = f"__acyclic_{idx}__"    # fully acyclic molecule: no ring scaffold, isolate as its own group
        scaffold_to_indices[scaffold].append(idx)
    if n_invalid:
        print(f"WARNING: {n_invalid} molecule(s) had unparseable SMILES; each was isolated as its own scaffold group.")

    # Shuffle (for reproducibility/tie-breaking) then sort scaffold groups largest-first
    rng = np.random.default_rng(seed)
    scaffold_groups = list(scaffold_to_indices.values())
    order = rng.permutation(len(scaffold_groups))
    scaffold_groups = [scaffold_groups[i] for i in order]
    scaffold_groups.sort(key=len, reverse=True)

    n_total = len(indices)
    n_train_target = int(np.floor(train_ratio * n_total))
    n_val_target = int(np.floor(val_ratio * n_total))

    train_idx, val_idx, test_idx = [], [], []
    for group in scaffold_groups:
        if len(train_idx) + len(group) <= n_train_target:
            train_idx.extend(group)
        elif len(val_idx) + len(group) <= n_val_target:
            val_idx.extend(group)
        else:
            test_idx.extend(group)

    return np.array(train_idx), np.array(val_idx), np.array(test_idx)


train_idx, val_idx, test_idx = scaffold_split_indices(
    df1.index.to_numpy(),
    df1['smiles'].to_numpy(),
    y_label,
    train_ratio=0.6,
    val_ratio=0.2,
    seed=42
)

print("Train size:", len(train_idx))
print("Val size:", len(val_idx))
print("Test size:", len(test_idx))

# --- Diagnostics: class distribution per split, and explicit leakage/coverage checks ---
y_series = pd.Series(np.asarray(y_label), index=df1.index.to_numpy())
class_names = {0: "AA", 1: "AI", 2: "IA", 3: "II"}  # adjust if your label encoding differs

print("\nClass distribution per split:")
dist_table = pd.DataFrame({
    "Train": y_series.loc[train_idx].value_counts(),
    "Val":   y_series.loc[val_idx].value_counts(),
    "Test":  y_series.loc[test_idx].value_counts(),
}).fillna(0).astype(int).sort_index()
dist_table.index = dist_table.index.map(lambda c: class_names.get(c, c))
print(dist_table)

# Correctness checks: no leakage, full coverage
all_idx = set(train_idx) | set(val_idx) | set(test_idx)
assert all_idx == set(df1.index.to_numpy()), "Index coverage mismatch after scaffold split!"
assert len(set(train_idx) & set(val_idx)) == 0, "Leakage detected: train/val overlap!"
assert len(set(train_idx) & set(test_idx)) == 0, "Leakage detected: train/test overlap!"
assert len(set(val_idx) & set(test_idx)) == 0, "Leakage detected: val/test overlap!"
print("\nNo scaffold leakage between splits; full coverage confirmed.")

# Explicit warning for any class missing (0 examples) from a split -- this WILL
# happen with small classes under scaffold splitting and needs your attention,
# not silent failure downstream (e.g. in classification_report or training).
for split_name, idx in [("Train", train_idx), ("Val", val_idx), ("Test", test_idx)]:
    present_classes = set(y_series.loc[idx].unique())
    missing = set(class_names) - present_classes
    if missing:
        missing_names = [class_names[c] for c in missing]
        print(f"\n*** WARNING: {split_name} split has ZERO examples of class(es): {missing_names} ***")
        print("    This is a known risk of scaffold splitting with small classes (e.g. IA, n=10).")
        print("    Review before proceeding -- consider a different seed, a coarser scaffold")
        print("    (e.g. generic/skeleton scaffold), or explicitly discussing this limitation.")

Train size: 1567
Val size: 522
Test size: 523

Class distribution per split:
    Train  Val  Test
AA    137   65    64
AI     45   19    20
IA    649  191   167
II    736  247   272

No scaffold leakage between splits; full coverage confirmed.

In [34]:
svd = TruncatedSVD(n_components=256, random_state=42)
X = svd.fit_transform(node_features)

In [35]:
X.shape

(2612, 256)

In [36]:
#Mutual k-NN graph (with normalized squared weights)
k = 15
max_w = np.max(similarity_matrix ** 2)

edges = set()
for i in range(num_nodes):
    sims = similarity_matrix[i]
    nn_idx = np.argsort(sims)[::-1][1:k+1]
    for j in nn_idx:
        edges.add((i, j))

G = nx.Graph()
#G.add_nodes_from(range(num_nodes))  # keep isolated nodes

for i, j in edges:
    if (j, i) in edges:
        w = (similarity_matrix[i, j] ** 2) / max_w
        G.add_edge(i, j, weight=w)

In [37]:
G.number_of_nodes(), G.number_of_edges()

(2591, 13503)

In [38]:
#Convert to PyG Data object
edge_index = []
edge_attr = []

for u, v, data in G.edges(data=True):
    edge_index.append([u, v])
    edge_index.append([v, u])
    edge_attr.append([data["weight"]])
    edge_attr.append([data["weight"]])

edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous()
edge_attr = torch.tensor(edge_attr, dtype=torch.float)

x = torch.tensor(X, dtype=torch.float)
y = torch.tensor(y_label, dtype=torch.long)

data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)
data.num_classes = len(np.unique(y_label))

In [39]:
data

Data(x=[2612, 256], edge_index=[2, 27006], edge_attr=[27006, 1], y=[2612], num_classes=4)

In [40]:
#Create inductive subgraphs
#Training graph (only training nodes)
from torch_geometric.utils import subgraph

device = data.edge_index.device
train_idx = torch.as_tensor(train_idx).to(device)


train_edge_index, train_edge_weight = subgraph(
    train_idx,
    data.edge_index,
    data.edge_attr,
    relabel_nodes=True,
    num_nodes=data.num_nodes
)

train_data = Data(
    x=data.x[train_idx],
    y=data.y[train_idx],
    edge_index=train_edge_index,
    edge_weight=train_edge_weight
)

In [41]:
train_data

Data(x=[1567, 256], edge_index=[2, 16176], y=[1567], edge_weight=[16176, 1])

In [42]:
data.x[train_idx].shape, data.x[val_idx].shape, data.x[test_idx].shape

(torch.Size([1567, 256]), torch.Size([522, 256]), torch.Size([523, 256]))

In [43]:
#Validation graph (train + val nodes)

#Validation is still inductive relative to test nodes:
val_idx = torch.as_tensor(val_idx).to(device)
train_idx = torch.as_tensor(train_idx).to(device)

train_val_idx = torch.cat([train_idx, val_idx])

val_edge_index, val_edge_weight = subgraph(
    train_val_idx,
    data.edge_index,
    data.edge_attr,
    relabel_nodes=True,
    num_nodes=data.num_nodes
)

val_data = Data(
    x=data.x[train_val_idx],
    y=data.y[train_val_idx],
    edge_index=val_edge_index,
    edge_weight=val_edge_weight
)

# Mask for validation nodes (important!)
val_mask = torch.zeros(train_val_idx.size(0), dtype=torch.bool)
val_mask[torch.isin(train_val_idx, val_idx)] = True
val_data.val_mask = val_mask

In [44]:
#Test graph (train + val + test nodes)
test_edge_index, test_edge_weight = data.edge_index, data.edge_attr

test_data = Data(
    x=data.x,
    y=data.y,
    edge_index=test_edge_index,
    edge_weight=test_edge_weight
)

test_data.test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
test_data.test_mask[test_idx] = True

In [45]:
train_data

Data(x=[1567, 256], edge_index=[2, 16176], y=[1567], edge_weight=[16176, 1])

In [46]:
val_data

Data(x=[2089, 256], edge_index=[2, 20850], y=[2089], edge_weight=[20850, 1], val_mask=[2089])

In [47]:
test_data

Data(x=[2612, 256], edge_index=[2, 27006], y=[2612], edge_weight=[27006, 1], test_mask=[2612])

In [48]:
data

Data(x=[2612, 256], edge_index=[2, 27006], edge_attr=[27006, 1], y=[2612], num_classes=4)

In [49]:
G.number_of_nodes()

2591

In [50]:
data.edge_attr.shape

torch.Size([27006, 1])

In [51]:
data.x.shape

torch.Size([2612, 256])

In [52]:
data.has_self_loops(), data.has_isolated_nodes()

(True, True)

In [53]:
data.x[train_idx].shape

torch.Size([1567, 256])

In [54]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve, RocCurveDisplay, auc, roc_auc_score, matthews_corrcoef

In [119]:
#This config has been run on the 256-dimension normalized data
model = RandomForestClassifier(random_state=42, class_weight='balanced')
params = {'criterion': ['gini', 'entropy'],  'max_depth': list(range(3, 20, 2)), 'max_features': ['sqrt', 'log2', None], 'bootstrap': [True, False]}
grid = GridSearchCV(model, params, cv=5, n_jobs=-1, scoring='f1_macro')
grid.fit(data.x[train_idx], data.y[train_idx])

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                       15, 16, 17, 18, 19],
                         'max_features': ['sqrt', 'log2', None]})

In [55]:
#With scaffold_splitting:
model_rf = RandomForestClassifier(max_depth=3, class_weight='balanced', random_state=42)

In [56]:
#With 256 dimension
model_rf.fit(data.x[train_idx], data.y[train_idx])

RandomForestClassifier(class_weight='balanced', max_depth=3, random_state=42)

In [57]:
#Test set
py_test = model_rf.predict(test_data.x[test_data.test_mask].cpu())
print(classification_report(test_data.y[test_data.test_mask].cpu(), py_test))

              precision    recall  f1-score   support

           0       0.25      0.39      0.30        64
           1       0.07      0.05      0.06        20
           2       0.49      0.70      0.58       167
           3       0.65      0.41      0.51       272

    accuracy                           0.49       523
   macro avg       0.37      0.39      0.36       523
weighted avg       0.53      0.49      0.49       523

In [58]:
matthews_corrcoef(test_data.y[test_data.test_mask], py_test)

0.23528865838815696

In [59]:
#Test set
py_test = model_rf.predict(data.x[test_idx].cpu())
print(classification_report(data.y[test_idx].cpu(), py_test))

              precision    recall  f1-score   support

           0       0.25      0.39      0.30        64
           1       0.07      0.05      0.06        20
           2       0.49      0.70      0.58       167
           3       0.65      0.41      0.51       272

    accuracy                           0.49       523
   macro avg       0.37      0.39      0.36       523
weighted avg       0.53      0.49      0.49       523

In [60]:
#With 256 dimension
roc_auc_score(data.y[test_idx], model_rf.predict_proba(data.x[test_idx]), multi_class='ovr', average='macro')

0.6348056535077204

In [61]:
#With 256 dimension
roc_auc_score(data.y[test_idx], model_rf.predict_proba(data.x[test_idx]), multi_class='ovr', average=None)

array([0.59660948, 0.68081511, 0.73440759, 0.52739044])

In [62]:
py_test = model_rf.predict(test_data.x[test_data.test_mask].cpu())
confusion_matrix(data.y[test_data.test_mask], py_test)

array([[ 25,   4,  16,  19],
       [  5,   1,   3,  11],
       [ 20,   1, 117,  29],
       [ 50,   9, 101, 112]])

In [63]:
y_true = test_data.y[test_data.test_mask]
y_pred_rf = model_rf.predict(test_data.x[test_data.test_mask].cpu())

In [64]:
#Node classification task

In [65]:
data.edge_attr.shape

torch.Size([27006, 1])

In [66]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

Using device: cuda

In [67]:
#Similarity values are used in the train() function as edge_weight=data.edge_attr

In [68]:
import time

In [69]:
import torch
from torch import nn
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import scatter

In [70]:
class WeightedSAGEConv(MessagePassing):
    def __init__(self, in_channels, out_channels, bias=True):
        super().__init__(aggr='add')  # aggregation method: weighted sum
        self.lin = nn.Linear(in_channels, out_channels, bias=bias)

    def forward(self, x, edge_index, edge_weight):
        # x: [N, F]
        # edge_index: [2, E]
        # edge_weight: [E]
        return self.propagate(edge_index, x=x, edge_weight=edge_weight)

    def message(self, x_j, edge_weight):
        # x_j: neighbor features
        return edge_weight.view(-1, 1) * x_j

    def update(self, aggr_out):
        # Linear transformation after aggregation
        return self.lin(aggr_out)

In [71]:
#PyG’s SAGEConv uses mean by default
#If you want to use weighted-mean GraphSAGE aggregation:

In [72]:
from torch_geometric.utils import scatter

class WeightedMeanSAGEConv(MessagePassing):
    def __init__(self, in_channels, out_channels):
        super().__init__(aggr='add')
        self.lin = torch.nn.Linear(in_channels, out_channels)

    def forward(self, x, edge_index, edge_weight=None):
        if edge_weight is None:
            edge_weight = x.new_ones(edge_index.size(1))

        self.edge_weight = edge_weight
        return self.propagate(edge_index, x=x)

    def message(self, x_j):
        return x_j * self.edge_weight.view(-1, 1)

    def aggregate(self, inputs, index):
        weighted_sum = scatter(inputs, index, dim=0, reduce='sum')
        weight_sum = scatter(
            self.edge_weight, index, dim=0, reduce='sum'
        ).view(-1, 1)

        return weighted_sum / (weight_sum + 1e-8)

    def update(self, aggr_out):
        return self.lin(aggr_out)

In [73]:
import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout
from torch_geometric.nn import BatchNorm

class GraphSAGE(torch.nn.Module):
    def __init__(self, num_features, num_classes):
        super().__init__()
        #torch.manual_seed(1234)

        self.conv1 = WeightedMeanSAGEConv(num_features, 64)
        self.bn1 = BatchNorm(64)

        self.conv2 = WeightedMeanSAGEConv(64, 32)
        self.bn2 = BatchNorm(32)

        self.conv3 = WeightedMeanSAGEConv(32, 16)

        # Skip connections
        self.skip1 = Linear(num_features, 64) if num_features != 64 else None
        self.skip2 = Linear(64, 32)
        self.skip3 = Linear(32, 16)

        self.classifier = Linear(16, num_classes)
        self.dropout = Dropout(p=0.4)

    def forward(self, x, edge_index, edge_weight):
        # ---- Layer 1 ----
        residual = self.skip1(x) if self.skip1 is not None else x
        h = self.conv1(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.bn1(h)
        h = h + residual
        h = self.dropout(h)

        # ---- Layer 2 ----
        residual = self.skip2(h)
        h = self.conv2(h, edge_index, edge_weight)
        h = F.relu(h)
        h = self.bn2(h)
        h = h + residual
        h = self.dropout(h)

        # ---- Layer 3 ----
        residual = self.skip3(h)
        h = self.conv3(h, edge_index, edge_weight)
        h = h + residual

        out = self.classifier(h)
        return F.log_softmax(out, dim=-1), h

In [74]:
# =========================================================
# Inductive GraphSAGE training / validation / test (ONE CELL)
# =========================================================

import torch
import torch.nn.functional as F
from sklearn.metrics import f1_score

# -------- Setup --------
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_data = train_data.to(device)
val_data = val_data.to(device)
test_data = test_data.to(device)

model = GraphSAGE(
    num_features=train_data.x.size(1),
    num_classes=int(train_data.y.max()) + 1
).to(device)

class_counts = torch.bincount(train_data.y)
class_weights = (1.0 / class_counts.float())
class_weights = class_weights / class_weights.sum() * len(class_counts)  # normalize
class_weights = class_weights.to(device)
print("Class weights:", class_weights.tolist())

criterion = torch.nn.NLLLoss(weight=class_weights)

optimizer = torch.optim.Adam(
    model.parameters(), lr=0.01, weight_decay=5e-4
)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)

# -------- Train --------
def train(data):
    model.train()
    optimizer.zero_grad()

    out, h = model(data.x, data.edge_index, data.edge_weight)
    loss = criterion(out, data.y)

    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
    optimizer.step()
    scheduler.step()
    
    pred = out.argmax(dim=1)
    acc = (pred == data.y).float().mean()

    return loss, h, acc, out


# -------- Evaluate (Val / Test) --------
@torch.no_grad()
def evaluate(data, mask):
    model.eval()
    with torch.no_grad():
        out, h = model(data.x, data.edge_index, data.edge_weight)
        loss = criterion(out[mask], data.y[mask])
        pred = out[mask].argmax(dim=1)
        acc = (pred == data.y[mask]).float().mean()
        f1_macro = f1_score(data.y[mask].cpu(), pred.cpu(), average='macro', zero_division=0)
    return loss, acc, f1_macro, h, out


# -------- Training loop with early stopping --------
best_val_f1 = 0.0
patience, trials = 50, 0

print(
    "GraphSAGE (Inductive) | Train/Val/Test nodes:",
    f"{train_data.num_nodes}/"
    f"{val_data.val_mask.sum().item()}/"
    f"{test_data.test_mask.sum().item()}"
)

for epoch in range(1, 201):
    loss_train, h, acc_train, out = train(train_data)
    loss_val, acc_val, f1_val, _, _ = evaluate(val_data, val_data.val_mask)

    # Early stopping + checkpoint
    if f1_val > best_val_f1:     # was: acc_val > best_val_acc
        best_val_f1 = f1_val
        trials = 0
        torch.save(model.state_dict(), "best_graphSAGE_inductive.pt")
    else:
        trials += 1

    if epoch % 10 == 0:
        print(
            f"Epoch {epoch:03d} | "
            f"Train Loss: {loss_train:.4f} | Train Acc: {acc_train:.4f} | "
            f"Val Loss: {loss_val:.4f} | Val Acc: {acc_val:.4f} | "
            f"Best: {best_val_f1:.4f}"
        )

    if trials >= patience:
        print(f"Early stopping at epoch {epoch}")
        break


# -------- Test --------
checkpoint = torch.load("best_graphSAGE_inductive.pt", map_location=device)
model.load_state_dict(checkpoint)

loss_test, acc_test, f1, h_test, out_test = evaluate(
    test_data, test_data.test_mask
)

print(f"GraphSAGE Test Loss: {loss_test:.4f} | Test Acc: {acc_test:.4f}")

Class weights: [0.9005601406097412, 2.7417054176330566, 0.19010284543037415, 0.16763144731521606]
GraphSAGE (Inductive) | Train/Val/Test nodes: 1567/522/523
Epoch 010 | Train Loss: 0.6501 | Train Acc: 0.6605 | Val Loss: 1.9350 | Val Acc: 0.5613 | Best: 0.3416
Epoch 020 | Train Loss: 0.5528 | Train Acc: 0.7090 | Val Loss: 2.3687 | Val Acc: 0.5172 | Best: 0.3416
Epoch 030 | Train Loss: 0.4779 | Train Acc: 0.7339 | Val Loss: 2.5388 | Val Acc: 0.5019 | Best: 0.3418
Epoch 040 | Train Loss: 0.4135 | Train Acc: 0.7588 | Val Loss: 3.3011 | Val Acc: 0.4732 | Best: 0.3418
Epoch 050 | Train Loss: 0.3990 | Train Acc: 0.7658 | Val Loss: 3.9627 | Val Acc: 0.4540 | Best: 0.3418
Epoch 060 | Train Loss: 0.3493 | Train Acc: 0.7805 | Val Loss: 4.5235 | Val Acc: 0.4444 | Best: 0.3418
Epoch 070 | Train Loss: 0.2959 | Train Acc: 0.7907 | Val Loss: 4.9324 | Val Acc: 0.4598 | Best: 0.3418
Epoch 080 | Train Loss: 0.3208 | Train Acc: 0.8022 | Val Loss: 5.3445 | Val Acc: 0.4847 | Best: 0.3523
Epoch 090 | Train Loss: 0.2784 | Train Acc: 0.8143 | Val Loss: 5.4280 | Val Acc: 0.4789 | Best: 0.3548
Epoch 100 | Train Loss: 0.2667 | Train Acc: 0.8290 | Val Loss: 6.1494 | Val Acc: 0.4751 | Best: 0.3548
Epoch 110 | Train Loss: 0.2466 | Train Acc: 0.8296 | Val Loss: 6.3923 | Val Acc: 0.4636 | Best: 0.3548
Epoch 120 | Train Loss: 0.2323 | Train Acc: 0.8424 | Val Loss: 6.6893 | Val Acc: 0.4559 | Best: 0.3548
Epoch 130 | Train Loss: 0.2318 | Train Acc: 0.8437 | Val Loss: 6.9772 | Val Acc: 0.4540 | Best: 0.3548
Early stopping at epoch 131
GraphSAGE Test Loss: 6.5206 | Test Acc: 0.4799

/tmp/ipykernel_44397/1286817838.py:103: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load("best_graphSAGE_inductive.pt", map_location=device)

In [75]:
from sklearn.metrics import classification_report

# Ground truth and predictions for test nodes
y_true = test_data.y[test_data.test_mask].cpu()
y_pred = out_test[test_data.test_mask].argmax(dim=1).cpu()

# Print classification report
print(classification_report(y_true, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.169     0.188     0.178        64
           1      0.042     0.100     0.059        20
           2      0.515     0.527     0.521       167
           3      0.639     0.548     0.590       272

    accuracy                          0.480       523
   macro avg      0.341     0.341     0.337       523
weighted avg      0.519     0.480     0.497       523

In [76]:
matthews_corrcoef(y_true, y_pred)

0.1936414122521912

In [77]:
y_pred_gsage = y_pred

In [78]:
import numpy as np
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.preprocessing import label_binarize

def gnn_auc_scores(out, y, mask, n_classes=4):
    """out: log-softmax output [N, C] for ALL nodes (what model(...) returns first);
    y: labels [N]; mask: boolean test mask [N].
    Returns macro one-vs-rest AUROC, per-class AUROC, macro AUPRC, per-class AUPRC."""
    probs = out[mask].exp().detach().cpu().numpy().astype("float64")
    probs = probs / probs.sum(axis=1, keepdims=True)      # guard against tiny float32 drift
    y_np = y[mask].cpu().numpy()
    auroc_macro = roc_auc_score(y_np, probs, multi_class="ovr", average="macro")
    auroc_pc = roc_auc_score(y_np, probs, multi_class="ovr", average=None)
    y_bin = label_binarize(y_np, classes=list(range(n_classes)))
    auprc_pc = np.array([average_precision_score(y_bin[:, c], probs[:, c]) for c in range(n_classes)])
    return auroc_macro, auroc_pc, auprc_pc.mean(), auprc_pc

In [79]:
# out_test is the full-graph output your evaluate() already returns
auroc_macro, auroc_pc, auprc_macro, auprc_pc = gnn_auc_scores(out_test, test_data.y, test_data.test_mask)
print(f"Macro AUROC (OvR): {auroc_macro:.4f} | Macro AUPRC: {auprc_macro:.4f}")
for c, name in enumerate(["AA", "AI", "IA", "II"]):
    print(f"  {name}: AUROC={auroc_pc[c]:.4f}  AUPRC={auprc_pc[c]:.4f}")

Macro AUROC (OvR): 0.6114 | Macro AUPRC: 0.3680
  AA: AUROC=0.6191  AUPRC=0.1827
  AI: AUROC=0.4822  AUPRC=0.0406
  IA: AUROC=0.6934  AUPRC=0.5711
  II: AUROC=0.6511  AUPRC=0.6777

## Multi-run evaluation (10 seeds, fixed) — added to correct for run-to-run variability from unfixed GNN initialization.

Each run uses `set_seed(seed)` for `seed in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` (python/numpy/torch/cuda RNGs), trains GraphSAGE from scratch with early stopping (same protocol as the single-run cells above), and evaluates on the same fixed 226-node test set. Results are aggregated as mean +/- std across the 10 runs.

In [80]:
# ==========================================================================
# Multi-run aggregation helper (mean +/- std across seeds)
# ==========================================================================
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, matthews_corrcoef

CLASS_NAMES = ["AA", "AI", "IA", "II"]  # label order: 0=AA, 1=AI, 2=IA, 3=II

def summarize_runs(all_y_true, all_y_pred, all_acc, all_mcc, model_name, out_prefix):
    """
    all_y_true / all_y_pred: lists of numpy arrays, one pair per run (same
        test set each time, so all_y_true[i] should be identical across runs
        -- kept per-run only for safety/verification).
    all_acc / all_mcc: lists of floats, one per run.
    Returns (overall_df, per_class_df) and writes them to CSV.
    """
    n_runs = len(all_acc)

    reports = [
        classification_report(
            yt, yp, labels=list(range(len(CLASS_NAMES))),
            target_names=CLASS_NAMES, output_dict=True, zero_division=0
        )
        for yt, yp in zip(all_y_true, all_y_pred)
    ]
    # NEW: macro-F1 per run, pulled directly from each run's classification_report
    # -- directly tracks minority-class performance across seeds, the whole point
    # of the class-weighting + F1-based model-selection fix.
    all_f1_macro = [r["macro avg"]["f1-score"] for r in reports]

    overall_df = pd.DataFrame({
        "Metric": ["Accuracy", "MCC", "Macro_F1"],
        "Mean": [np.mean(all_acc), np.mean(all_mcc), np.mean(all_f1_macro)],
        "Std":  [np.std(all_acc),  np.std(all_mcc),  np.std(all_f1_macro)],
        "N_runs": [n_runs, n_runs, n_runs],
    })

    rows = []
    for cname in CLASS_NAMES:
        precisions = [r[cname]["precision"] for r in reports]
        recalls    = [r[cname]["recall"]    for r in reports]
        f1s        = [r[cname]["f1-score"]  for r in reports]
        rows.append({
            "Class": cname,
            "Precision_mean": np.mean(precisions), "Precision_std": np.std(precisions),
            "Recall_mean":    np.mean(recalls),    "Recall_std":    np.std(recalls),
            "F1_mean":        np.mean(f1s),        "F1_std":        np.std(f1s),
        })
    per_class_df = pd.DataFrame(rows)

    print(f"\n=== {model_name}: overall performance across {n_runs} runs (mean +/- std) ===")
    print(overall_df.to_string(index=False, float_format=lambda x: f"{x:.4f}"))

    print(f"\n=== {model_name}: per-class performance across {n_runs} runs (mean +/- std) ===")
    print(per_class_df.to_string(index=False, float_format=lambda x: f"{x:.4f}"))

    overall_df.to_csv(f"{out_prefix}_overall_multirun.csv", index=False)
    per_class_df.to_csv(f"{out_prefix}_per_class_multirun.csv", index=False)
    print(f"\nSaved: {out_prefix}_overall_multirun.csv, {out_prefix}_per_class_multirun.csv")

    return overall_df, per_class_df

In [81]:
# ==========================================================================
# GraphSAGE: fixed-seed, 10-run training for mean +/- std reporting
# (accuracy, MCC, per-class P/R/F1 via summarize_runs; plus AUROC / AUPRC)
# ==========================================================================
import numpy as np
import pandas as pd
from sklearn.metrics import (f1_score, matthews_corrcoef, roc_auc_score,
                             average_precision_score)
from sklearn.preprocessing import label_binarize

CLASS_NAMES = ["AA", "AI", "IA", "II"]

def gnn_auc_scores(out, y, mask, n_classes=4):
    """out: log-softmax output [N, C] for ALL nodes (what model(...) returns first);
    y: labels [N]; mask: boolean test mask [N].
    Returns macro one-vs-rest AUROC, per-class AUROC, macro AUPRC, per-class AUPRC."""
    probs = out[mask].exp().detach().cpu().numpy().astype("float64")
    probs = probs / probs.sum(axis=1, keepdims=True)      # guard against tiny float32 drift
    y_np = y[mask].cpu().numpy()
    auroc_macro = roc_auc_score(y_np, probs, multi_class="ovr", average="macro")
    auroc_pc = roc_auc_score(y_np, probs, multi_class="ovr", average=None)
    y_bin = label_binarize(y_np, classes=list(range(n_classes)))
    auprc_pc = np.array([average_precision_score(y_bin[:, c], probs[:, c]) for c in range(n_classes)])
    return auroc_macro, auroc_pc, auprc_pc.mean(), auprc_pc

SEEDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# class_weights computed ONCE outside the loop -- train_data.y is identical
# across all 10 seeds (only the model's random initialization differs)
class_counts = torch.bincount(train_data.y)
class_weights = (1.0 / class_counts.float())
class_weights = class_weights / class_weights.sum() * len(class_counts)
class_weights = class_weights.to(device)
print("Class weights:", class_weights.tolist())
criterion = torch.nn.NLLLoss(weight=class_weights)

all_y_true, all_y_pred, all_acc, all_mcc = [], [], [], []
all_auroc_macro, all_auroc_pc, all_auprc_macro, all_auprc_pc = [], [], [], []

for run_idx, seed in enumerate(SEEDS):
    set_seed(seed)  # resets python/numpy/torch(+cuda) RNG state for this run

    model = GraphSAGE(num_features=train_data.x.size(1),
                             num_classes=int(train_data.y.max()) + 1).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)

    def train_step(data):
        model.train()
        optimizer.zero_grad()
        out, h = model(data.x, data.edge_index, data.edge_weight)
        loss = criterion(out, data.y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        pred = out.argmax(dim=1)
        acc = (pred == data.y).float().mean()
        return loss, acc

    @torch.no_grad()
    def eval_step(data, mask):
        model.eval()
        out, h = model(data.x, data.edge_index, data.edge_weight)
        loss = criterion(out[mask], data.y[mask])
        pred = out[mask].argmax(dim=1)
        acc = (pred == data.y[mask]).float().mean()
        f1_macro = f1_score(data.y[mask].cpu(), pred.cpu(), average="macro", zero_division=0)
        return loss, acc, f1_macro, out

    best_val_f1 = 0.0
    patience, trials = 50, 0
    best_state = None
    ckpt_path = f"best_graphSAGE_inductive_multirun_seed{seed}.pt"

    for epoch in range(1, 201):
        loss_train, acc_train = train_step(train_data)
        loss_val, acc_val, f1_val, _ = eval_step(val_data, val_data.val_mask)

        if f1_val > best_val_f1:
            best_val_f1 = f1_val
            trials = 0
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            trials += 1
        if trials >= patience:
            break

    # ---- final test evaluation with the best (validation macro-F1) checkpoint ----
    model.load_state_dict(best_state)
    loss_test, acc_test, f1_test, out_test = eval_step(test_data, test_data.test_mask)

    # AUROC / AUPRC: must come AFTER out_test has been computed for THIS seed
    am, apc, pm, ppc = gnn_auc_scores(out_test, test_data.y, test_data.test_mask)
    all_auroc_macro.append(am); all_auroc_pc.append(apc)
    all_auprc_macro.append(pm); all_auprc_pc.append(ppc)

    y_true_run = test_data.y[test_data.test_mask].cpu().numpy()
    y_pred_run = out_test[test_data.test_mask].argmax(dim=1).cpu().numpy()
    mcc_run = matthews_corrcoef(y_true_run, y_pred_run)

    all_y_true.append(y_true_run)
    all_y_pred.append(y_pred_run)
    all_acc.append(acc_test.item())
    all_mcc.append(mcc_run)

    print(f"[GraphSAGE] Run {run_idx+1}/{len(SEEDS)} (seed={seed}): "
          f"Test Acc={acc_test.item():.4f}, Test F1(macro)={f1_test:.4f}, MCC={mcc_run:.4f}, "
          f"AUROC(macro)={am:.4f}, best epoch val_f1={best_val_f1:.4f}")

# ---- aggregate AUROC / AUPRC across seeds (population SD, same convention as the other multirun CSVs) ----
A, P = np.array(all_auroc_pc), np.array(all_auprc_pc)
rows = [{"Class": "macro",
         "AUROC_mean": np.mean(all_auroc_macro), "AUROC_std": np.std(all_auroc_macro),
         "AUPRC_mean": np.mean(all_auprc_macro), "AUPRC_std": np.std(all_auprc_macro)}]
for c, name in enumerate(CLASS_NAMES):
    rows.append({"Class": name,
                 "AUROC_mean": A[:, c].mean(), "AUROC_std": A[:, c].std(),
                 "AUPRC_mean": P[:, c].mean(), "AUPRC_std": P[:, c].std()})
auc_df = pd.DataFrame(rows)
auc_df.to_csv("gsage_auc_multirun.csv", index=False)   # change the prefix per architecture
print("\n=== GraphSAGE: AUROC / AUPRC across", len(SEEDS), "runs (mean +/- std) ===")
print(auc_df.round(4).to_string(index=False))

overall_graphSAGE, per_class_graphSAGE = summarize_runs(
    all_y_true, all_y_pred, all_acc, all_mcc,
    model_name="GraphSAGE", out_prefix="gsage"
)

Class weights: [0.9005601406097412, 2.7417054176330566, 0.19010284543037415, 0.16763144731521606]
[GraphSAGE] Run 1/10 (seed=0): Test Acc=0.5048, Test F1(macro)=0.3365, MCC=0.2128, AUROC(macro)=0.6549, best epoch val_f1=0.3553
[GraphSAGE] Run 2/10 (seed=1): Test Acc=0.5545, Test F1(macro)=0.3667, MCC=0.2485, AUROC(macro)=0.6700, best epoch val_f1=0.3655
[GraphSAGE] Run 3/10 (seed=2): Test Acc=0.5143, Test F1(macro)=0.3698, MCC=0.2341, AUROC(macro)=0.6404, best epoch val_f1=0.4131
[GraphSAGE] Run 4/10 (seed=3): Test Acc=0.4914, Test F1(macro)=0.3342, MCC=0.2038, AUROC(macro)=0.6327, best epoch val_f1=0.3871
[GraphSAGE] Run 5/10 (seed=4): Test Acc=0.5545, Test F1(macro)=0.3652, MCC=0.2644, AUROC(macro)=0.6634, best epoch val_f1=0.3673
[GraphSAGE] Run 6/10 (seed=5): Test Acc=0.5411, Test F1(macro)=0.3613, MCC=0.2602, AUROC(macro)=0.6507, best epoch val_f1=0.3816
[GraphSAGE] Run 7/10 (seed=6): Test Acc=0.5220, Test F1(macro)=0.3593, MCC=0.2432, AUROC(macro)=0.6552, best epoch val_f1=0.3707
[GraphSAGE] Run 8/10 (seed=7): Test Acc=0.5086, Test F1(macro)=0.3778, MCC=0.2357, AUROC(macro)=0.6574, best epoch val_f1=0.3640
[GraphSAGE] Run 9/10 (seed=8): Test Acc=0.4914, Test F1(macro)=0.3331, MCC=0.1982, AUROC(macro)=0.6401, best epoch val_f1=0.3777
[GraphSAGE] Run 10/10 (seed=9): Test Acc=0.5277, Test F1(macro)=0.3594, MCC=0.2492, AUROC(macro)=0.6390, best epoch val_f1=0.3507

=== GraphSAGE: AUROC / AUPRC across 10 runs (mean +/- std) ===
Class  AUROC_mean  AUROC_std  AUPRC_mean  AUPRC_std
macro      0.6504     0.0114      0.3748     0.0063
   AA      0.5824     0.0561      0.1863     0.0298
   AI      0.6452     0.0563      0.0762     0.0378
   IA      0.7231     0.0086      0.5746     0.0229
   II      0.6507     0.0110      0.6621     0.0198

=== GraphSAGE: overall performance across 10 runs (mean +/- std) ===
  Metric   Mean    Std  N_runs
Accuracy 0.5210 0.0222      10
     MCC 0.2350 0.0218      10
Macro_F1 0.3563 0.0151      10

=== GraphSAGE: per-class performance across 10 runs (mean +/- std) ===
Class  Precision_mean  Precision_std  Recall_mean  Recall_std  F1_mean  F1_std
   AA          0.2244         0.0580       0.2328      0.0697   0.2235  0.0503
   AI          0.0976         0.1588       0.0300      0.0332   0.0395  0.0482
   IA          0.5139         0.0294       0.6036      0.0485   0.5530  0.0168
   II          0.6524         0.0117       0.5743      0.0560   0.6093  0.0302

Saved: gsage_overall_multirun.csv, gsage_per_class_multirun.csv